apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - image: us-east4-docker.pkg.dev/enterprise-service-bus-410800/gateway/production
        name: gateway
        env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: connectionString
          - name: PORT
            value: '3004'
          - name: AUTH_HOST
            value: auth
          - name: AUTH_PORT
            value: '3002'
          - name: PAYMENTS_HOST
            value: payments
          - name: PAYMENTS_PORT
            value: '3001'