services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - gateway
      - auth
      - payments
      - notifications
      - mongo
  gateway:
    image: us-east4-docker.pkg.dev/enterprise-service-bus-410800/gateway/production
    env_file:
      - ../apps/gateway/.env
    ports:
      - 3000:3000
  auth:
    image: us-east4-docker.pkg.dev/enterprise-service-bus-410800/auth/production
    env_file:
      - ../apps/auth/.env
    ports:
      - 3001:3001
  payments:
    image: us-east4-docker.pkg.dev/enterprise-service-bus-410800/payments/production
    env_file:
      - ../apps/payments/.env
    ports:
      - 3003:3003
  notifications:
    image: us-east4-docker.pkg.dev/enterprise-service-bus-410800/notifications/production
    env_file:
      - ../apps/notifications/.env
    ports:
      - 3004:3004
  mongo:
    image: mongo